/**
 * Phosphor Icons bridge — maps string icon names to Phosphor components.
 * Replaces `@expo/vector-icons` MaterialIcons across the app.
 *
 * Usage:
 *   import { AppIcon, type IconName } from "@/lib/icons";
 *   <AppIcon name="home" size={24} color="#fff" />
 */
import React from "react";
import type { IconWeight } from "phosphor-react-native";
import {
  AppleLogoIcon,
  ArrowClockwiseIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowsLeftRightIcon,
  ArrowSquareOutIcon,
  ArticleIcon,
  BabyIcon,
  BabyCarriageIcon,
  BagIcon,
  BarcodeIcon,
  BellIcon,
  BellRingingIcon,
  BellSlashIcon,
  BookOpenIcon,
  BookOpenTextIcon,
  BrainIcon,
  BreadIcon,
  BriefcaseIcon,
  BuildingsIcon,
  CameraIcon,
  CameraPlusIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpIcon,
  CellSignalFullIcon,
  ChartBarIcon,
  ChatCircleIcon,
  CheckIcon,
  CheckCircleIcon,
  ChecksIcon,
  CircleHalfIcon,
  CircleIcon,
  CloudArrowDownIcon,
  CloudSlashIcon,
  CompassIcon,
  CopyIcon,
  CreditCardIcon,
  CrossIcon,
  CrosshairIcon,
  CrownIcon,
  DotsThreeVerticalIcon,
  DropIcon,
  EggIcon,
  EnvelopeOpenIcon,
  EnvelopeSimpleIcon,
  EyeIcon,
  EyeSlashIcon,
  FactoryIcon,
  FileTextIcon,
  FireIcon,
  FirstAidIcon,
  FishSimpleIcon,
  FlagIcon,
  FlaskIcon,
  FlowerIcon,
  ForkKnifeIcon,
  GavelIcon,
  GearIcon,
  GiftIcon,
  GlobeIcon,
  GlobeHemisphereWestIcon,
  GrainsIcon,
  HamburgerIcon,
  HandshakeIcon,
  HandHeartIcon,
  HandPalmIcon,
  HandTapIcon,
  HeadsetIcon,
  HeartIcon,
  HeartbeatIcon,
  HouseIcon,
  IdentificationBadgeIcon,
  ImageIcon,
  ImageBrokenIcon,
  ImagesIcon,
  InfoIcon,
  InfinityIcon,
  LeafIcon,
  ListMagnifyingGlassIcon,
  LightningIcon,
  LightningSlashIcon,
  LockIcon,
  LockSimpleIcon,
  MagnifyingGlassIcon,
  MapPinIcon,
  MapPinAreaIcon,
  MapPinPlusIcon,
  MapTrifoldIcon,
  MedalIcon,
  MegaphoneIcon,
  MinusIcon,
  MinusCircleIcon,
  MoonIcon,
  MosqueIcon,
  NavigationArrowIcon,
  PackageIcon,
  PaletteIcon,
  PaperPlaneRightIcon,
  ParkIcon,
  PencilIcon,
  PhoneIcon,
  PillIcon,
  PlantIcon,
  PlayCircleIcon,
  PlusIcon,
  PlusCircleIcon,
  ProhibitIcon,
  ProhibitInsetIcon,
  QrCodeIcon,
  QuestionIcon,
  RadioButtonIcon,
  RecycleIcon,
  ScalesIcon,
  ScanIcon,
  ScissorsIcon,
  SealIcon,
  SealCheckIcon,
  ShareNetworkIcon,
  ShieldIcon,
  ShieldCheckIcon,
  ShieldWarningIcon,
  ShoppingCartIcon,
  ShoppingCartSimpleIcon,
  SignInIcon,
  SignOutIcon,
  SkullIcon,
  SlidersIcon,
  SmileyIcon,
  SmileyMehIcon,
  SmileySadIcon,
  SmileyWinkIcon,
  SparkleIcon,
  SpeakerHighIcon,
  SquaresFourIcon,
  StarIcon,
  StarFourIcon,
  StorefrontIcon,
  SunIcon,
  TagIcon,
  ThumbsDownIcon,
  ThumbsUpIcon,
  TrashIcon,
  TreeIcon,
  TrendUpIcon,
  TrophyIcon,
  TruckIcon,
  UserIcon,
  UserCircleIcon,
  UserPlusIcon,
  UsersIcon,
  UsersThreeIcon,
  WarehouseIcon,
  WarningIcon,
  WarningCircleIcon,
  WifiSlashIcon,
  XCircleIcon,
} from "phosphor-react-native";

// ── Mapping: kebab-case name → Phosphor component ──────────────────
const ICON_REGISTRY = {
  "add": PlusIcon,
  "add-a-photo": CameraPlusIcon,
  "add-circle-outline": PlusCircleIcon,
  "add-location": MapPinPlusIcon,
  "add-shopping-cart": ShoppingCartIcon,
  "agriculture": PlantIcon,
  "all-inclusive": InfinityIcon,
  "apple": AppleLogoIcon,
  "apps": SquaresFourIcon,
  "arrow-back": ArrowLeftIcon,
  "arrow-back-ios-new": CaretLeftIcon,
  "arrow-drop-down": CaretDownIcon,
  "arrow-forward": ArrowRightIcon,
  "arrow-forward-ios": CaretRightIcon,
  "article": ArticleIcon,
  "auto-awesome": SparkleIcon,
  "auto-stories": BookOpenTextIcon,
  "badge": IdentificationBadgeIcon,
  "bakery-dining": BreadIcon,
  "balance": ScalesIcon,
  "block": ProhibitIcon,
  "brightness-auto": CircleHalfIcon,
  "business": BriefcaseIcon,
  "call": PhoneIcon,
  "camera-alt": CameraIcon,
  "cancel": XCircleIcon,
  "card-giftcard": GiftIcon,
  "check": CheckIcon,
  "check-circle": CheckCircleIcon,
  "chevron-right": CaretRightIcon,
  "child-care": BabyCarriageIcon,
  "close": CrossIcon,
  "cloud-download": CloudArrowDownIcon,
  "cloud-off": CloudSlashIcon,
  "content-copy": CopyIcon,
  "content-cut": ScissorsIcon,
  "credit-card": CreditCardIcon,
  "dangerous": SkullIcon,
  "dark-mode": MoonIcon,
  "dashboard": ChartBarIcon,
  "delete": TrashIcon,
  "description": FileTextIcon,
  "directions": SignInIcon,
  "do-not-disturb-alt": ProhibitIcon,
  "done-all": ChecksIcon,
  "eco": LeafIcon,
  "edit": PencilIcon,
  "egg": EggIcon,
  "emoji-events": TrophyIcon,
  "error": WarningCircleIcon,
  "error-outline": WarningCircleIcon,
  "expand-less": CaretUpIcon,
  "expand-more": CaretDownIcon,
  "explore": CompassIcon,
  "face": UserCircleIcon,
  "fact-check": ChecksIcon,
  "factory": FactoryIcon,
  "fastfood": HamburgerIcon,
  "favorite": HeartIcon,
  "favorite-border": HeartIcon,
  "flag": FlagIcon,
  "flash-off": LightningSlashIcon,
  "flash-on": LightningIcon,
  "g-mobiledata": CellSignalFullIcon,
  "gavel": GavelIcon,
  "grain": GrainsIcon,
  "grass": PlantIcon,
  "groups": UsersThreeIcon,
  "hand-palm": HandPalmIcon,
  "handshake": HandshakeIcon,
  "health-and-safety": FirstAidIcon,
  "help": QuestionIcon,
  "help-outline": QuestionIcon,
  "history": ListMagnifyingGlassIcon,
  "home": HouseIcon,
  "image": ImageIcon,
  "image-not-supported": ImageBrokenIcon,
  "info": InfoIcon,
  "info-outline": InfoIcon,
  "inventory-2": PackageIcon,
  "keyboard-arrow-down": CaretDownIcon,
  "language": GlobeIcon,
  "leaderboard": ChartBarIcon,
  "light-mode": SunIcon,
  "local-fire-department": FireIcon,
  "local-offer": TagIcon,
  "local-shipping": TruckIcon,
  "location-city": BuildingsIcon,
  "location-on": MapPinIcon,
  "location-searching": CrosshairIcon,
  "lock": LockIcon,
  "lock-outline": LockSimpleIcon,
  "login": SignInIcon,
  "logout": SignOutIcon,
  "mail": EnvelopeSimpleIcon,
  "mail-outline": EnvelopeSimpleIcon,
  "map": MapTrifoldIcon,
  "mark-email-read": EnvelopeOpenIcon,
  "medication": PillIcon,
  "menu-book": BookOpenIcon,
  "military-tech": MedalIcon,
  "monitor-heart": HeartbeatIcon,
  "moon": MoonIcon,
  "more-vert": DotsThreeVerticalIcon,
  "mosque": MosqueIcon,
  "my-location": CrosshairIcon,
  "near-me": NavigationArrowIcon,
  "new-releases": MegaphoneIcon,
  "no-food": ProhibitInsetIcon,
  "notification-important": BellRingingIcon,
  "notifications": BellRingingIcon,
  "notifications-active": BellRingingIcon,
  "notifications-none": BellIcon,
  "notifications-off": BellSlashIcon,
  "offline-bolt": LightningIcon,
  "open-in-new": ArrowSquareOutIcon,
  "palette": PaletteIcon,
  "park": ParkIcon,
  "people": UsersIcon,
  "person": UserIcon,
  "person-add": UserPlusIcon,
  "person-outline": UserIcon,
  "person-pin": MapPinAreaIcon,
  "phishing": FishSimpleIcon,
  "phone": PhoneIcon,
  "photo-camera": CameraIcon,
  "photo-library": ImagesIcon,
  "place": MapPinIcon,
  "play-circle-outline": PlayCircleIcon,
  "pregnant-woman": BabyIcon,
  "privacy-tip": ShieldWarningIcon,
  "psychology": BrainIcon,
  "public": GlobeHemisphereWestIcon,
  "qr-code": QrCodeIcon,
  "qr-code-2": QrCodeIcon,
  "qr-code-scanner": BarcodeIcon,
  "radio-button-checked": RadioButtonIcon,
  "radio-button-unchecked": CircleIcon,
  "rate-review": ChatCircleIcon,
  "recycling": RecycleIcon,
  "redeem": TagIcon,
  "refresh": ArrowClockwiseIcon,
  "remove": MinusIcon,
  "remove-circle-outline": MinusCircleIcon,
  "report-problem": WarningCircleIcon,
  "restaurant": ForkKnifeIcon,
  "restaurant-menu": ForkKnifeIcon,
  "schedule": ArrowClockwiseIcon,
  "science": FlaskIcon,
  "search": MagnifyingGlassIcon,
  "search-off": MagnifyingGlassIcon,
  "send": PaperPlaneRightIcon,
  "sentiment-dissatisfied": SmileyMehIcon,
  "sentiment-neutral": SmileyMehIcon,
  "sentiment-satisfied": SmileyIcon,
  "sentiment-very-dissatisfied": SmileySadIcon,
  "sentiment-very-satisfied": SmileyWinkIcon,
  "set-meal": FishSimpleIcon,
  "settings": GearIcon,
  "share": ShareNetworkIcon,
  "shield": ShieldIcon,
  "shield-moon": ShieldIcon,
  "shield-warning": ShieldWarningIcon,
  "shopping-bag": BagIcon,
  "shopping-cart": ShoppingCartIcon,
  "shopping-cart-checkout": ShoppingCartSimpleIcon,
  "spa": FlowerIcon,
  "star": StarIcon,
  "star-border": StarIcon,
  "stars": StarFourIcon,
  "store": StorefrontIcon,
  "storefront": StorefrontIcon,
  "sun": SunIcon,
  "support-agent": HeadsetIcon,
  "swap-horiz": ArrowsLeftRightIcon,
  "thumb-down": ThumbsDownIcon,
  "thumb-up": ThumbsUpIcon,
  "touch-app": HandTapIcon,
  "travel-explore": GlobeHemisphereWestIcon,
  "trending-up": TrendUpIcon,
  "tune": SlidersIcon,
  "verified": SealCheckIcon,
  "verified-user": ShieldCheckIcon,
  "visibility": EyeIcon,
  "visibility-off": EyeSlashIcon,
  "volume-up": SpeakerHighIcon,
  "volunteer-activism": HandHeartIcon,
  "warehouse": WarehouseIcon,
  "warning": WarningIcon,
  "water-drop": DropIcon,
  "wifi-off": WifiSlashIcon,
  "workspace-premium": CrownIcon,
  // direct phosphor names
  "seal": SealIcon,
  "clock": ArrowClockwiseIcon,
} as const;

export type IconName = keyof typeof ICON_REGISTRY;

export interface AppIconProps {
  name: IconName;
  size?: number;
  color?: string;
  weight?: IconWeight;
  style?: any;
}

export function AppIcon({
  name,
  size = 24,
  color,
  weight = "regular",
  style,
}: AppIconProps) {
  const Component = ICON_REGISTRY[name];
  if (!Component) return null;
  return <Component size={size} color={color} weight={weight} style={style} />;
}

export { ICON_REGISTRY };
