/**
 * BDS Boycott Seed Data
 *
 * Sources:
 * - BDS Movement: https://bdsmovement.net/Guide-to-BDS-Boycott
 * - Ethical Consumer: https://www.ethicalconsumer.org/ethical-campaigns-boycotts/palestine-boycott-list
 *
 * Last updated: 2026-02-14
 */

import type { NewBoycottTarget } from "../schema/boycott.js";

export const BDS_SEED_DATA: NewBoycottTarget[] = [
  // ── NIVEAU 1 — Cibles Prioritaires BDS (Boycott officiel) ──

  {
    companyName: "Chevron",
    brands: ["Chevron", "Caltex", "Texaco"],
    parentCompany: "Chevron Corporation",
    sector: "Énergie / Pétrole",
    boycottLevel: "official_bds",
    severity: "critical",
    reason: "Principale multinationale extractant le gaz revendiqué par l'apartheid israélien en Méditerranée orientale. Chevron a acquis Noble Energy en 2020, héritant des contrats d'extraction dans les eaux revendiquées par les Palestiniens.",
    reasonSummary: "Extraction de gaz en Méditerranée Est — territoire revendiqué par la Palestine",
    sourceUrl: "https://bdsmovement.net/chevron",
    sourceName: "BDS Movement",
    verifiedBy: "BDS Official",
    isActive: true,
  },
  {
    companyName: "Intel",
    brands: ["Intel"],
    parentCompany: "Intel Corporation",
    sector: "Technologie / Semi-conducteurs",
    boycottLevel: "official_bds",
    severity: "critical",
    reason: "Plus grand investisseur international en Israël. Usine construite sur les terres palestiniennes ethniquement nettoyées de Kiryat Gat.",
    reasonSummary: "Plus gros investisseur étranger en Israël — usine sur terre palestinienne",
    sourceUrl: "https://bdsmovement.net/intel",
    sourceName: "BDS Movement",
    verifiedBy: "BDS Official",
    isActive: true,
  },
  {
    companyName: "Dell Technologies",
    brands: ["Dell", "Alienware", "Dell EMC"],
    parentCompany: "Dell Technologies Inc.",
    sector: "Technologie / Matériel",
    boycottLevel: "official_bds",
    severity: "critical",
    reason: "Fournit l'armée israélienne (contrat de $150M en 2023). Le PDG Michael Dell a fait don de $350M à Israël.",
    reasonSummary: "Fournisseur militaire israélien — $150M de contrats",
    sourceUrl: "https://bdsmovement.net/dell",
    sourceName: "BDS Movement",
    verifiedBy: "BDS Official",
    isActive: true,
  },
  {
    companyName: "Siemens",
    brands: ["Siemens"],
    parentCompany: "Siemens AG",
    sector: "Industrie / Ingénierie",
    boycottLevel: "official_bds",
    severity: "critical",
    reason: "Contractant principal du câble sous-marin Euro-Asia Interconnector reliant les colonies israéliennes illégales à l'Europe.",
    reasonSummary: "Connecte les colonies israéliennes à l'Europe via câble sous-marin",
    sourceUrl: "https://bdsmovement.net/siemens",
    sourceName: "BDS Movement",
    verifiedBy: "BDS Official",
    isActive: true,
  },
  {
    companyName: "Hewlett Packard",
    brands: ["HP", "HPE", "HP Inc"],
    parentCompany: "HP Inc. / Hewlett Packard Enterprise",
    sector: "Technologie / Impression",
    boycottLevel: "official_bds",
    severity: "critical",
    reason: "Soutient l'armée, les prisons et la police israéliennes. Fournit la technologie aux checkpoints et colonies illégales.",
    reasonSummary: "Technologie pour l'armée, les prisons et les checkpoints",
    sourceUrl: "https://bdsmovement.net/hp",
    sourceName: "BDS Movement",
    verifiedBy: "BDS Official",
    isActive: true,
  },
  {
    companyName: "Microsoft",
    brands: ["Microsoft", "Xbox", "LinkedIn", "GitHub", "Azure", "Bing"],
    parentCompany: "Microsoft Corporation",
    sector: "Technologie / Cloud",
    boycottLevel: "official_bds",
    severity: "critical",
    reason: "Fournit Azure Cloud et services IA à l'armée israélienne. Sciemment complice dans l'utilisation de technologie pour la surveillance et les opérations militaires.",
    reasonSummary: "Azure Cloud + IA fournis à l'armée israélienne",
    sourceUrl: "https://bdsmovement.net/microsoft",
    sourceName: "BDS Movement",
    verifiedBy: "BDS Official",
    isActive: true,
  },
  {
    companyName: "Carrefour",
    brands: ["Carrefour", "Carrefour Bio", "Carrefour City"],
    parentCompany: "Carrefour SA",
    sector: "Distribution / Retail",
    boycottLevel: "official_bds",
    severity: "critical",
    reason: "Partenariat avec des entreprises de colonies. Soutien aux soldats israéliens. Opère dans les colonies illégales.",
    reasonSummary: "Partenaire des colonies israéliennes — soutien soldats",
    sourceUrl: "https://bdsmovement.net/carrefour",
    sourceName: "BDS Movement",
    verifiedBy: "BDS Official",
    isActive: true,
  },
  {
    companyName: "AXA",
    brands: ["AXA"],
    parentCompany: "AXA SA",
    sector: "Finance / Assurance",
    boycottLevel: "official_bds",
    severity: "critical",
    reason: "Détient plus de $150M dans des entreprises armant Israël (Boeing, General Dynamics).",
    reasonSummary: "$150M+ investis dans Boeing et General Dynamics qui arment Israël",
    sourceUrl: "https://bdsmovement.net/axa",
    sourceName: "BDS Movement",
    verifiedBy: "BDS Official",
    isActive: true,
  },
  {
    companyName: "Disney",
    brands: ["Disney", "Disney+", "Marvel", "Star Wars", "Hulu", "ESPN"],
    parentCompany: "The Walt Disney Company",
    sector: "Divertissement / Streaming",
    boycottLevel: "official_bds",
    severity: "warning",
    reason: "Complice dans la glorification du régime d'apartheid. Emploie des ambassadeurs culturels israéliens.",
    reasonSummary: "Glorification culturelle du régime — ambassadeurs israéliens",
    sourceUrl: "https://bdsmovement.net/disney",
    sourceName: "BDS Movement",
    verifiedBy: "BDS Official",
    isActive: true,
  },
  {
    companyName: "SodaStream",
    brands: ["SodaStream"],
    parentCompany: "PepsiCo (via acquisition)",
    sector: "Boissons / Électroménager",
    boycottLevel: "official_bds",
    severity: "warning",
    reason: "Complice dans le déplacement des citoyens Bédouins-Palestiniens dans le Naqab.",
    reasonSummary: "Déplacement de Bédouins-Palestiniens dans le Naqab",
    sourceUrl: "https://bdsmovement.net/sodastream",
    sourceName: "BDS Movement",
    verifiedBy: "BDS Official",
    isActive: true,
  },

  // ── NIVEAU 2 — Boycott Populaire (grassroots, soutenu par BDS) ──

  {
    companyName: "McDonald's",
    brands: ["McDonald's", "McCafé", "McDelivery"],
    sector: "Restauration rapide",
    boycottLevel: "grassroots",
    severity: "warning",
    reason: "Franchise McDonald's Israël a offert des repas gratuits aux soldats pendant les opérations militaires. Campagne de boycott massive mondiale.",
    reasonSummary: "Repas gratuits aux soldats israéliens pendant les opérations militaires",
    sourceUrl: "https://bdsmovement.net/economic-boycott",
    sourceName: "BDS Movement",
    verifiedBy: "BDS Grassroots",
    isActive: true,
  },
  {
    companyName: "Coca-Cola",
    brands: ["Coca-Cola", "Coca-Cola Zero", "Fanta", "Sprite", "Minute Maid", "Fuze Tea", "Powerade"],
    parentCompany: "The Coca-Cola Company",
    sector: "Boissons",
    boycottLevel: "grassroots",
    severity: "warning",
    reason: "Présence majeure en Israël via Central Bottling Company (CBC). Investissements significatifs dans l'économie israélienne.",
    reasonSummary: "Investissements massifs dans l'économie israélienne via CBC",
    sourceUrl: "https://bdsmovement.net/economic-boycott",
    sourceName: "BDS Movement",
    verifiedBy: "BDS Grassroots",
    isActive: true,
  },
  {
    companyName: "Burger King",
    brands: ["Burger King"],
    sector: "Restauration rapide",
    boycottLevel: "grassroots",
    severity: "warning",
    reason: "Opère des franchises en Israël, contribuant à l'économie de l'apartheid.",
    reasonSummary: "Franchises en Israël — contribution à l'économie d'apartheid",
    sourceUrl: "https://bdsmovement.net/economic-boycott",
    sourceName: "BDS Movement",
    verifiedBy: "BDS Grassroots",
    isActive: true,
  },
  {
    companyName: "Papa John's",
    brands: ["Papa John's"],
    sector: "Restauration rapide",
    boycottLevel: "grassroots",
    severity: "warning",
    reason: "Opère des franchises en Israël.",
    reasonSummary: "Franchises en Israël",
    sourceUrl: "https://bdsmovement.net/economic-boycott",
    sourceName: "BDS Movement",
    verifiedBy: "BDS Grassroots",
    isActive: true,
  },
  {
    companyName: "Pizza Hut",
    brands: ["Pizza Hut"],
    sector: "Restauration rapide",
    boycottLevel: "grassroots",
    severity: "warning",
    reason: "Opère des franchises en Israël.",
    reasonSummary: "Franchises en Israël",
    sourceUrl: "https://bdsmovement.net/economic-boycott",
    sourceName: "BDS Movement",
    verifiedBy: "BDS Grassroots",
    isActive: true,
  },
  {
    companyName: "Domino's Pizza",
    brands: ["Domino's", "Domino's Pizza"],
    sector: "Restauration rapide",
    boycottLevel: "grassroots",
    severity: "warning",
    reason: "Opère des franchises en Israël.",
    reasonSummary: "Franchises en Israël",
    sourceUrl: "https://bdsmovement.net/economic-boycott",
    sourceName: "BDS Movement",
    verifiedBy: "BDS Grassroots",
    isActive: true,
  },

  // ── NIVEAU 3 — Cibles Pression (campagnes en cours) ──

  {
    companyName: "Google",
    brands: ["Google", "YouTube", "Android", "Chrome", "Gmail", "Google Cloud"],
    parentCompany: "Alphabet Inc.",
    sector: "Technologie / Cloud",
    boycottLevel: "pressure",
    severity: "warning",
    reason: "Projet Nimbus : contrat cloud et IA avec l'armée israélienne. Utilisé dans les programmes de ciblage 'Lavender' et 'Gospel'.",
    reasonSummary: "Projet Nimbus — IA + Cloud pour l'armée israélienne",
    sourceUrl: "https://bdsmovement.net/google-amazon",
    sourceName: "BDS Movement",
    verifiedBy: "BDS Official",
    isActive: true,
  },
  {
    companyName: "Amazon",
    brands: ["Amazon", "AWS", "Prime", "Alexa", "Twitch", "Whole Foods"],
    parentCompany: "Amazon.com Inc.",
    sector: "Technologie / E-commerce",
    boycottLevel: "pressure",
    severity: "warning",
    reason: "Projet Nimbus : contrat cloud avec l'armée israélienne. Services AWS utilisés pour la surveillance et les opérations militaires.",
    reasonSummary: "Projet Nimbus — Cloud AWS pour l'armée israélienne",
    sourceUrl: "https://bdsmovement.net/google-amazon",
    sourceName: "BDS Movement",
    verifiedBy: "BDS Official",
    isActive: true,
  },
  {
    companyName: "Booking.com",
    brands: ["Booking.com", "Booking"],
    parentCompany: "Booking Holdings",
    sector: "Voyage / Hébergement",
    boycottLevel: "pressure",
    severity: "info",
    reason: "Propose des locations dans les colonies israéliennes illégales sur territoire palestinien volé.",
    reasonSummary: "Locations dans les colonies israéliennes illégales",
    sourceUrl: "https://bdsmovement.net/travel",
    sourceName: "BDS Movement",
    verifiedBy: "BDS Official",
    isActive: true,
  },
];
