/**
 * Google Places seed — called by run-all.ts
 *
 * Seeds stores with Google Places enrichment data (ratings, photos, reviews, hours)
 * from a static JSON export. This ensures ALL environments (dev, preview, production)
 * have consistent Google data without requiring GOOGLE_PLACES_API_KEY.
 *
 * Data source: assets/google-places-data.json
 * Generated by: _export-google-places.ts (run manually after enrichment)
 *
 * Idempotent: uses sourceId matching + ON CONFLICT upserts.
 */

import type { PostgresJsDatabase } from "drizzle-orm/postgres-js";
import { eq, sql } from "drizzle-orm";
import { readFileSync, existsSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_PATH = resolve(__dirname, "../../../asset/google-places-data.json");

interface GooglePlacesExport {
  exportedAt: string;
  stores: Array<{
    sourceId: string | null;
    googlePlaceId: string | null;
    googleMapsUrl: string | null;
    googleRating: number | null;
    googleReviewCount: number | null;
    googlePhotos: string[] | null;
    imageUrl: string | null;
    phone: string | null;
    website: string | null;
  }>;
  reviews: Record<
    string,
    Array<{
      googleReviewId: string;
      authorName: string;
      authorPhotoUri: string | null;
      rating: number;
      text: string | null;
      publishTime: string | null;
      relativeTime: string | null;
      languageCode: string | null;
    }>
  >;
  hours: Record<
    string,
    Array<{
      dayOfWeek: number;
      openTime: string | null;
      closeTime: string | null;
      isClosed: boolean;
    }>
  >;
}

export async function seedGooglePlaces(db: PostgresJsDatabase): Promise<number> {
  if (!existsSync(DATA_PATH)) {
    console.log("      (no google-places-data.json found — skipping)");
    return 0;
  }

  const raw = readFileSync(DATA_PATH, "utf-8");
  const data: GooglePlacesExport = JSON.parse(raw);

  if (!data.stores || data.stores.length === 0) return 0;

  let updatedStores = 0;
  let insertedReviews = 0;
  let insertedHours = 0;

  for (const store of data.stores) {
    if (!store.sourceId) continue;

    // Find store by sourceId (stable across environments)
    const [existing] = await db.execute(
      sql`SELECT id, google_place_id FROM stores WHERE source_id = ${store.sourceId} LIMIT 1`
    );
    if (!existing) continue;

    const storeId = existing.id as string;

    // Update Google fields on the store
    await db.execute(sql`
      UPDATE stores SET
        google_place_id = ${store.googlePlaceId},
        google_maps_url = ${store.googleMapsUrl},
        google_rating = ${store.googleRating},
        google_review_count = ${store.googleReviewCount},
        google_photos = ${JSON.stringify(store.googlePhotos ?? [])}::jsonb,
        google_enriched_at = NOW(),
        image_url = COALESCE(${store.imageUrl}, image_url),
        phone = COALESCE(${store.phone}, phone),
        website = COALESCE(${store.website}, website),
        updated_at = NOW()
      WHERE id = ${storeId}
    `);
    updatedStores++;

    // Upsert google_reviews
    const reviews = data.reviews[store.sourceId] ?? [];
    for (const review of reviews) {
      await db.execute(sql`
        INSERT INTO google_reviews (store_id, google_review_id, author_name, author_photo_uri, rating, text, publish_time, relative_time, language_code)
        VALUES (
          ${storeId},
          ${review.googleReviewId},
          ${review.authorName},
          ${review.authorPhotoUri},
          ${review.rating},
          ${review.text},
          ${review.publishTime ? new Date(review.publishTime) : null},
          ${review.relativeTime},
          ${review.languageCode ?? "fr"}
        )
        ON CONFLICT (google_review_id) DO UPDATE SET
          rating = EXCLUDED.rating,
          text = EXCLUDED.text,
          relative_time = EXCLUDED.relative_time,
          updated_at = NOW()
      `);
      insertedReviews++;
    }

    // Seed store_hours (delete-then-insert for this store to avoid stale hours)
    const hours = data.hours[store.sourceId] ?? [];
    if (hours.length > 0) {
      // Only replace hours if we have Google data for this store
      // (don't delete hours that came from Achahada seed)
      const [existingHoursCount] = await db.execute(
        sql`SELECT count(*)::int AS c FROM store_hours WHERE store_id = ${storeId}`
      );
      const hasExistingHours = (existingHoursCount?.c as number) > 0;

      // If store already has hours from another seed, skip (don't overwrite)
      if (!hasExistingHours) {
        for (const h of hours) {
          await db.execute(sql`
            INSERT INTO store_hours (store_id, day_of_week, open_time, close_time, is_closed)
            VALUES (${storeId}, ${h.dayOfWeek}, ${h.openTime}, ${h.closeTime}, ${h.isClosed})
          `);
          insertedHours++;
        }
      }
    }
  }

  console.log(`      (${updatedStores} stores, ${insertedReviews} reviews, ${insertedHours} hours)`);
  return updatedStores;
}
